# ===============================
# DATASOURCE - POSTGRES (Docker)
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:musicdb}
spring.datasource.username=${DB_USER:music}
spring.datasource.password=${DB_PASS:music}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# SWAGGER 
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ===============================
# MINIO 
# ===============================
minio.url=http://localhost:9000
minio.public-url=http://localhost:9000
minio.user=admin
minio.pass=admin123
minio.bucket=capas

#===============================
#Health/Liveness/Readiness
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Habilita probes do Kubernetes / Docker
management.health.probes.enabled=true
